### ISSUE TITLE
Snowflake enhancements

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#161]
A list of Snowflake enhancements to be handled in bulk

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/plugin-jdbc/issues/138
- [ ] https://github.com/kestra-io/plugin-jdbc/issues/160
- [ ] blueprints for [Dynamic tables](https://docs.snowflake.com/en/user-guide/dynamic-tables-about) (requested by consulting partner)
- [ ] add a [Snowpipe Streaming](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-overview) blueprint based on Synergy request
```

**Comment by anna-geller** [comment]
closing as old enhancement and no customer asked so far
